REFERENCE="/home/mccrone/variant_pipeline/tutorial/data/reference/wsn33_wt_plasmid"
REFERENCE_FA="/home/mccrone/variant_pipeline/tutorial/data/reference/wsn33_wt_plasmid.fa"
SCRIPTS="/home/mccrone/variant_pipeline/scripts"
LIBRARY_LOCATION="/home/mccrone/variant_pipeline/lib"
CONTROL="Plasmid_control"
DISP="two.sided"
